[CSE 276F Submission] PlaceSphere
haosulab/ManiSkill pull request #379
Opened 2024-06-12 02:40 UTC by astonastonaston

The task involves grasping a sphere and placing that on top of a little bin. The task is solvable via ppo in 5000_0000 epochs.

Training command: python ppo.py --env_id="PlaceSphere-v1" \
  --num_envs=1024 --update_epochs=8 --num_minibatches=32 \
  --total_timesteps=50_000_000

Evaluation command: python ppo.py --env_id="PlaceSphere-v1"   --evaluate --checkpoint=/path_to_final_ckpt.pt  --num_eval_envs=1 --num-eval-steps=1000 --seed=2

Evaluation results:
eval_success_rate=0.8478260869565217

2024-06-13 21:10 UTC, StoneT2000 commented
Work looks good. Just resolve conflicts with main and see my comments. Can confirm RL works as well.

2024-06-13 22:09 UTC, astonastonaston commented
Conflicts resolved. I re-structured a bit and hopefully I didn't make their RollBall docs wrong.

2024-06-13 23:15 UTC, StoneT2000 commented
> Conflicts resolved. I re-structured a bit and hopefully I didn't make their RollBall docs wrong.

Still missing fixes for the 2 reviewed parts. see comments above

2024-06-14 01:18 UTC, astonastonaston commented
> > Conflicts resolved. I re-structured a bit and hopefully I didn't make their RollBall docs wrong.
> 
> Still missing fixes for the 2 reviewed parts. see comments above


I can't see any comment in the code... Could you specify where they are?

2024-06-14 05:10 UTC, StoneT2000 requested changes

2024-06-14 05:10 UTC, StoneT2000 commented on mani_skill/envs/tasks/tabletop/place_sphere.py
> +        success = is_obj_on_bin * is_obj_static * (~is_obj_grasped)
the "*" can just be "&" symbols. This removes the need to do unnecessary type casting in the line below with .bool

2024-06-14 05:10 UTC, StoneT2000 commented on mani_skill/envs/tasks/tabletop/place_sphere.py
> +if __name__ == "__main__":
remove this script here below.

2024-06-14 05:37 UTC, astonastonaston commented
Okay now the 2 parts are fixed

2024-06-14 07:16 UTC, StoneT2000 approved these changes

2024-06-14 07:16 UTC, merged